function decodeEntities(s=''){return s.replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n)))}
function htmlToText(html=''){return decodeEntities(html).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<(br|\/p|\/div|\/li|\/h[1-6]|\/section|\/article|\/tr)>/gi,'\n').replace(/<li[^>]*>/gi,'• ').replace(/<[^>]+>/g,' ').replace(/[ \t]+/g,' ').replace(/\n\s*\n+/g,'\n').trim()}
function arr(x){return Array.isArray(x)?x:(x?[x]:[])}
function findJob(obj){if(!obj)return null;if(Array.isArray(obj)){for(const x of obj){const y=findJob(x);if(y)return y}return null}if(typeof obj==='object'){const t=obj['@type'];if(t==='JobPosting'||(Array.isArray(t)&&t.includes('JobPosting')))return obj;if(obj['@graph']){const y=findJob(obj['@graph']);if(y)return y}for(const v of Object.values(obj)){if(typeof v==='object'){const y=findJob(v);if(y)return y}}}return null}
function first(re,s){const m=String(s||'').match(re);return m?m[1].trim():''}
function isoDateFromDE(s){const m=String(s||'').match(/(\d{1,2})\.(\d{1,2})\.(\d{4})/);if(!m)return'';return `${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`}
export default async function handler(req,res){try{const raw=String(req.query.url||'');let u;try{u=new URL(raw)}catch{throw new Error('Ungültiger Link')}if(!/^https?:$/.test(u.protocol))throw new Error('Nur http/https Links sind erlaubt');const r=await fetch(u.toString(),{headers:{'user-agent':'Mozilla/5.0 (compatible; BewerbungCommandCenter/1.0)','accept-language':'de-DE,de;q=0.9,en;q=0.7'}});if(!r.ok)throw new Error(`Seite antwortet mit ${r.status}`);const html=await r.text();let job=null;for(const m of html.matchAll(/<script[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const obj=JSON.parse(decodeEntities(m[1]).trim());const f=findJob(obj);if(f){job=f;break}}catch{}}
const pageText=htmlToText(html);let title='',company='',city='',address='',contactPerson='',contactRole='',contactEmail='',deadline='',description='';if(job){title=job.title||'';company=job.hiringOrganization?.name||'';const loc=arr(job.jobLocation)[0]||{};const a=loc.address||{};city=a.addressLocality||'';address=[a.streetAddress,a.postalCode,a.addressLocality].filter(Boolean).join(', ');description=htmlToText(job.description||'');if(job.validThrough)deadline=String(job.validThrough).slice(0,10)}
if(!title)title=first(/(?:^|\n)(Ausbildung[^\n]{3,120})/i,pageText)||first(/<title[^>]*>([^<]+)<\/title>/i,html);
if(!company){company=first(/(?:^|\n)([A-ZÄÖÜ][^\n]{2,80}(?:Hotel|Hotels|Restaurant|GmbH|AG|Resort|Hostel|Hospitality)[^\n]*)/i,pageText)}
if(!address){address=first(/(?:📍\s*)?([^\n,]{2,80}\s+-\s+[^\n]*\b\d{5}\s+[A-Za-zÄÖÜäöüß -]+)/i,pageText)||first(/([A-Za-zÄÖÜäöüß .-]+\s+\d+[a-zA-Z]?,\s*\d{5}\s+[A-Za-zÄÖÜäöüß -]+)/,pageText)}
if(!city&&address){city=first(/\b\d{5}\s+([A-Za-zÄÖÜäöüß -]{2,50})$/,address)}
const cpBlock=first(/(?:Deine Kontaktperson|Ansprechpartner(?:in)?|Kontaktperson)\s*\n?([\s\S]{0,180})/i,pageText);if(cpBlock){const lines=cpBlock.split('\n').map(x=>x.trim()).filter(Boolean);if(lines[0]&&!/@/.test(lines[0])){const m=lines[0].match(/^([A-ZÄÖÜ][A-Za-zÄÖÜäöüß.-]+(?:\s+[A-ZÄÖÜ][A-Za-zÄÖÜäöüß.-]+){1,3})(?:\s+(.{3,60}))?$/);if(m){contactPerson=m[1];contactRole=(m[2]||'').trim()}}contactEmail=(cpBlock.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)||[])[0]||''}
if(!contactEmail)contactEmail=(pageText.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)||[])[0]||'';
if(!deadline){const d=first(/Bewerbungsfrist\s+([^\n]{3,40})/i,pageText);if(d&&!/laufend/i.test(d))deadline=isoDateFromDE(d)}
const text=(description||pageText).slice(0,80000);res.setHeader('Cache-Control','s-maxage=1800, stale-while-revalidate=86400');res.status(200).json({source:u.hostname,title:title.trim(),company:company.trim(),city:city.trim(),address:address.trim(),contactPerson:contactPerson.trim(),contactRole:contactRole.trim(),contactEmail:contactEmail.trim(),deadline,text})}catch(e){res.status(400).json({error:e.message||'Import fehlgeschlagen'})}}
