function decodeEntities(s=''){return String(s).replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#(\d+);/g,(_,n)=>String.fromCharCode(Number(n)))}
function htmlToText(html=''){return decodeEntities(html).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<(br|\/p|\/div|\/li|\/h[1-6]|\/section|\/article|\/tr)>/gi,'\n').replace(/<li[^>]*>/gi,'• ').replace(/<[^>]+>/g,' ').replace(/[ \t]+/g,' ').replace(/\n\s*\n+/g,'\n').trim()}
function arr(x){return Array.isArray(x)?x:(x?[x]:[])}
function first(re,s){const m=String(s||'').match(re);return m?String(m[1]||'').trim():''}
function clean(s=''){return String(s).replace(/\s+/g,' ').replace(/^[•·\-*\s]+/,'').trim()}
function findJob(obj){if(!obj)return null;if(Array.isArray(obj)){for(const x of obj){const y=findJob(x);if(y)return y}return null}if(typeof obj==='object'){const t=obj['@type'];if(t==='JobPosting'||(Array.isArray(t)&&t.includes('JobPosting')))return obj;if(obj['@graph']){const y=findJob(obj['@graph']);if(y)return y}for(const v of Object.values(obj)){if(typeof v==='object'){const y=findJob(v);if(y)return y}}}return null}
function isoToDE(s=''){const m=String(s).match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[3]}.${m[2]}.${m[1]}`:String(s||'')}
function isPrivateHost(host=''){host=host.toLowerCase().replace(/^\[|\]$/g,'');if(host==='localhost'||host.endsWith('.localhost'))return true;if(/^127\./.test(host)||/^10\./.test(host)||/^192\.168\./.test(host)||/^169\.254\./.test(host))return true;const m=host.match(/^172\.(\d+)\./);if(m&&Number(m[1])>=16&&Number(m[1])<=31)return true;if(host==='::1'||host.startsWith('fc')||host.startsWith('fd')||host.startsWith('fe80:'))return true;return false}
function safeUrl(raw){let u;try{u=new URL(String(raw||''))}catch{throw new Error('Ungültiger Link')}if(!/^https?:$/.test(u.protocol))throw new Error('Nur http/https Links sind erlaubt');if(isPrivateHost(u.hostname))throw new Error('Lokale/private Adressen sind nicht erlaubt');return u}
async function fetchPage(url){const u=safeUrl(url);const r=await fetch(u.toString(),{redirect:'follow',headers:{'user-agent':'Mozilla/5.0 (compatible; BewerbungCommandCenter/2.0)','accept-language':'de-DE,de;q=0.9,en;q=0.7'}});if(!r.ok)throw new Error(`Seite antwortet mit ${r.status}`);const finalUrl=safeUrl(r.url||u.toString());return {url:finalUrl.toString(),html:await r.text()}}
function jsonJobFromHtml(html=''){for(const m of html.matchAll(/<script[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const obj=JSON.parse(decodeEntities(m[1]).trim());const f=findJob(obj);if(f)return f}catch{}}return null}
function titleFromText(text=''){const lines=text.split('\n').map(clean).filter(Boolean);const c=lines.filter(x=>/(hotelfach|hotelmanagement|restaurant|koch|köchin|auszubild|ausbildung)/i.test(x)&&x.length<150);c.sort((a,b)=>{const sa=(/m\/w\/d|w\/m\/d|d\/w\/m/i.test(a)?3:0)+(/auszubild|ausbildung/i.test(a)?2:0)+a.length/100;const sb=(/m\/w\/d|w\/m\/d|d\/w\/m/i.test(b)?3:0)+(/auszubild|ausbildung/i.test(b)?2:0)+b.length/100;return sb-sa});return c[0]||''}
function pickBetterTitle(a='',b=''){a=clean(a);b=clean(b);if(!a)return b;if(!b)return a;const score=s=>(/m\/w\/d|w\/m\/d|d\/w\/m/i.test(s)?5:0)+(/auszubild|ausbildung/i.test(s)?2:0)+Math.min(2,s.length/60);return score(b)>score(a)?b:a}
function completeAddress(a={}){const street=clean(a.streetAddress||''),zip=clean(a.postalCode||''),city=clean(a.addressLocality||'');if(!street&&!zip)return'';return [street,[zip,city].filter(Boolean).join(' ')].filter(Boolean).join(', ')}
function addressFromText(text=''){return first(/([A-Za-zÄÖÜäöüß .,'’\-]+\s+\d+[a-zA-Z]?,\s*\d{5}\s+[A-Za-zÄÖÜäöüß .\-]+)/,text)||first(/([A-Za-zÄÖÜäöüß .,'’\-]+\s+\d+[a-zA-Z]?\s+\d{5}\s+[A-Za-zÄÖÜäöüß .\-]+)/,text)}
function cityFromAddress(address=''){return first(/\b\d{5}\s+([A-Za-zÄÖÜäöüß .\-]{2,50})$/,address)}
function contactFromText(text=''){let person='',role='',email='';email=(text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)||[])[0]||'';const m=text.match(/(?:Ansprechpartner(?:in)?|Kontaktperson|Deine Kontaktperson)\s*\n+([^\n]{2,90})(?:\n+([^\n]{2,90}))?/i);if(m){const p=clean(m[1]);if(!/@|bewerben|interesse geweckt|kontakt/i.test(p)&&/^[A-ZÄÖÜ][A-Za-zÄÖÜäöüß.'’\-]+(?:\s+[A-ZÄÖÜ][A-Za-zÄÖÜäöüß.'’\-]+){1,3}$/.test(p))person=p;const r=clean(m[2]||'');if(person&&r&&!/@|bewerben|interesse|telefon/i.test(r)&&r.length<70)role=r}return {person,role,email}}
function deadlineFromText(text=''){const d=first(/Bewerbungsfrist\s*\n?\s*([^\n]{2,50})/i,text);if(!d)return'';return clean(d.replace(/^[•: -]+/,''))}
function startFromText(text=''){const exact=first(/\bab\s+(\d{1,2}\.\d{1,2}\.\d{4})\b/i,text);if(exact)return exact;const s=first(/Frühester Beginn\s*\n?\s*([^\n]{2,60})/i,text);return clean(s)}
function companyUnitFromText(text='',city='',company=''){const lines=text.split('\n').map(clean).filter(Boolean).slice(0,45);let best='';for(let x of lines){if(x===company||x===city||x.length<5||x.length>120)continue;if(/^(bewerben|neu|was wir bieten|deine benefits|aufgaben|profil)$/i.test(x))continue;if(!/(hotel|dorint|resort|hostel|restaurant|apart|marriott|hilton|hyatt|accor|ibis|novotel|mercure|steigenberger|intercity)/i.test(x))continue;if(/gmbh| ag$|gesellschaft|betriebs/i.test(x)&&company)return best||'';if(city){const re=new RegExp(`\\s+${city.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}$`,'i');x=x.replace(re,'').trim()}if(!best||x.length>best.length)best=x}return best}
function extractApplyLinks(html='',baseUrl=''){const base=new URL(baseUrl),out=[];for(const m of html.matchAll(/<a\b([^>]*?)href=["']([^"']+)["']([^>]*)>([\s\S]*?)<\/a>/gi)){let u;try{u=new URL(decodeEntities(m[2]),base)}catch{continue}if(!/^https?:$/.test(u.protocol)||isPrivateHost(u.hostname))continue;const label=clean(htmlToText(m[4]));if(u.hostname===base.hostname)continue;let score=0;if(/jetzt bewerben|bewerben|zur bewerbung|online bewerben|apply/i.test(label))score+=10;if(/karriere|career|jobs|job|apply|bewerb|workday|personio|softgarden|recruitee/i.test(u.hostname+u.pathname))score+=5;if(score)out.push({url:u.toString(),label,score})}out.sort((a,b)=>b.score-a.score);return [...new Map(out.map(x=>[x.url,x])).values()].slice(0,3)}
function parsePage(html,url){const job=jsonJobFromHtml(html),text=htmlToText(html);let title='',company='',city='',address='',description='',deadline='',startDate='',locationName='';if(job){title=clean(job.title||'');company=clean(job.hiringOrganization?.name||'');const loc=arr(job.jobLocation)[0]||{};const a=loc.address||{};city=clean(a.addressLocality||'');address=completeAddress(a);locationName=clean(loc.name||job.jobLocationType||'');description=htmlToText(job.description||'');if(job.validThrough)deadline=isoToDE(job.validThrough);if(job.jobStartDate)startDate=isoToDE(job.jobStartDate)}
 title=pickBetterTitle(title,titleFromText(text));if(!company)company=first(/(?:^|\n)([A-ZÄÖÜ][^\n]{2,100}(?:Hotel|Hotels|Restaurant|GmbH|AG|Resort|Hostel|Hospitality)[^\n]*)/i,text);if(!address)address=addressFromText(text);if(!city&&address)city=cityFromAddress(address);if(!deadline)deadline=deadlineFromText(text);if(!startDate)startDate=startFromText(text);const c=contactFromText(text);if(!locationName)locationName=companyUnitFromText(text,city,company);return {url,text,job,title,company,city,address,contactPerson:c.person,contactRole:c.role,contactEmail:c.email,deadline,startDate,locationName,description,applyLinks:extractApplyLinks(html,url)}}
function betterAddress(a='',b=''){const score=s=>(/\d{5}/.test(s)?3:0)+(/\d/.test(s)?2:0)+(/,/.test(s)?1:0)+Math.min(2,String(s).length/50);return score(b)>score(a)?b:a}
function merge(primary,official){if(!official)return {...primary,sources:[{type:'portal',url:primary.url}]};const exactOfficialStart=/\d{1,2}\.\d{1,2}\.\d{4}/.test(official.startDate||'');return {
 ...primary,
 title:pickBetterTitle(primary.title,official.title),
 company:primary.company||official.company,
 city:official.city||primary.city,
 address:betterAddress(primary.address,official.address),
 contactPerson:official.contactPerson||primary.contactPerson,
 contactRole:official.contactRole||primary.contactRole,
 contactEmail:official.contactEmail||primary.contactEmail,
 deadline:primary.deadline||official.deadline,
 startDate:exactOfficialStart?official.startDate:(primary.startDate||official.startDate),
 locationName:official.locationName||primary.locationName,
 officialUrl:official.url,
 sources:[{type:'portal',url:primary.url},{type:'official',url:official.url}]
 }}
export default async function handler(req,res){try{const firstPage=await fetchPage(String(req.query.url||''));const primary=parsePage(firstPage.html,firstPage.url);let official=null;for(const c of primary.applyLinks){try{const p=await fetchPage(c.url);official=parsePage(p.html,p.url);if(official.contactPerson||official.address||official.startDate||official.locationName)break}catch{}}
 const data=merge(primary,official);const text=(primary.description||primary.text).slice(0,80000);res.setHeader('Cache-Control','s-maxage=900, stale-while-revalidate=3600');res.status(200).json({source:new URL(primary.url).hostname,title:clean(data.title),company:clean(data.company),hotelName:clean(data.locationName),city:clean(data.city),address:clean(data.address),contactPerson:clean(data.contactPerson),contactRole:clean(data.contactRole),contactEmail:clean(data.contactEmail),deadline:clean(data.deadline),startDate:clean(data.startDate),officialUrl:data.officialUrl||'',sources:data.sources||[],text})}catch(e){res.status(400).json({error:e.message||'Import fehlgeschlagen'})}}
